### ISSUE TITLE
Unable to find packagesbuild

### ISSUE THREAD

**Issue by digwanderlust** [jamesabel/osnap#1]
Perhaps I missed it in the documentation but I didn't see anything about installing whatever packages build is.  On OSX El Capitan I get the following exception.

```
raise CalledProcessError(retcode, cmd)
```

subprocess.CalledProcessError: Command '/usr/local/bin/packagesbuild pathlt.pkgproj' returned non-zero exit status 127

After a little bit of googling around it looks like this is or was part of xcode.  I have xcode installed but this doesn't seem to be on my system.  The docs should probably call this out explicitly with some installation instructions similar to NSIS

**Comment by jamesabel** [comment]
Ah, yes - I agree that's not very pretty.  It's looking for the Packages tool ( [http://s.sudre.free.fr/Software/Packages/about.html](http://s.sudre.free.fr/Software/Packages/about.html) ), which has to be installed separately.  I'll put in an explicit check for it and give a proper error message if it's not there.  Thanks!

**Comment by jamesabel** [comment]
Requirement added to docs and a check put in the code.
