### ISSUE TITLE
main.py must exist but not in the documentation.

### ISSUE THREAD

**Issue by digwanderlust** [jamesabel/osnap#2]
https://github.com/jamesabel/osnap/blob/master/osnap/installer.py#L26

Explicitly looks for main.py in the current working dir.  I assume this is used as the main entry point but not all packages uses main.py as the entry point.  If this is an actual requirement it should be documented.

**Comment by jamesabel** [comment]
OK - I'll put it in the documentation.  I'm writing the main docs now (up until this point I only had the 'quick start').  Thanks for the input!

**Comment by jamesabel** [comment]
Fixed in 0.0.4.  Added the requirement to the docs and added a check for the file in the code.
