### ISSUE TITLE
Add requests to install_requires

### ISSUE THREAD

**Issue by Siecje** [jamesabel/osnap#3]
I created a `venv` on Windows and tried to run 

``` shell
python -m osnap.osnapy
```

But [osnap/utils.py](https://github.com/jamesabel/osnap/blob/32984fd88a9c7dd0337b42e77bfa09881189c007/osnap/util.py#L9) requires `requests`.

**Comment by jamesabel** [comment]
Ah - good point.  I'll add this.  Thanks!

**Comment by Siecje** [comment]
Fixed with https://github.com/jamesabel/osnap/commit/dc7dd4fe30df0b50328e9571ccca3c45e4f641e4 and https://github.com/jamesabel/osnap/commit/72772ee01aedc910a723cd4948d5e5277fe5241c
